### ISSUE TITLE
Current version is not compatible with R version 3.5.0

### ISSUE THREAD

**Issue by SLGiHub** [validmeasures/odkr#10]
[provide general introduction to the issue logging and why it is relevant to this repository]

## Context
[provide more detailed introduction to the issue itself and why it is relevant]

## Process
[ordered list the process to finding and recreating the issue, example below]

## Expected result
[describe what you would expect to have resulted from this process]

## Current result
[describe what you you currently experience from this process, and thereby explain the bug]

## Possible Fix
[not obligatory, but suggest fixes or reasons for the bug]

## `name of issue` screenshot
[if relevant, include a screenshot]

**Comment by ernestguevarra** [comment]
Hi. Are you using the latest CRAN version? You might have noticed that `odkr` is not anymore available via CRAN. It was archived by CRAN reviewers soon after submission of `odkr` version 0.2.0 but the issues that they raised regarding the package were already existing in `odkr` version 0.1.0.

The issues they raised centred on two key issues:

1) Lack of runtime check for installed Java in the users operating software; and,
2) package writing directories into user's computer which is not allowed by CRAN.

We attempted to address issue 1 and released version 0.2.0 which we thought addressed the problem. For issue 2, existing package already addresses the issue but when version 0.2.0 was released, the issue resurfaced due to an error in the implementation of the get_briefcase() function.

We have decided to re-approach the development process for `oder` in a totally different direction by using a direct interface to the Java software used by ODK briefcase rather than just using the command line interface to ODK briefcase. This will most likely be released in a new package with a different name or a new package but using the same package name if CRAN allows it.

In the meantime, the current version (0.2.0) can be downloaded in R via Github and should not create any issue regardless of the R version. I am using R 3.5.0 and have `odkr` installed via Github.

Let me know if indeed there are still issues and I can spend time to sort that out accordingly.

**Comment by ernestguevarra** [comment]
Just checked through this last night and the main issue is that the current ODK Briefcase version (1.11.1) has some issues with the command line interface which is what `odkr` uses to perform its pull and push functions.

I am not sure if this is related to the issue you raise but just raising it here so you are aware. I will raise this point as a separate issue and get a fix out latest by tomorrow.

**Comment by SLGiHub** [comment]
Yes this was the main issue, the command line flags passed to version 11.1 had changed. ODKR 0.2.0 works fine with pre version 11 of briefcase.

**Comment by ernestguevarra** [comment]
Hi, sorry for delay in reply and thank your your feedback. I have been in touch with ODK developers so the current development version of `odkr` should work now.

I am hoping to find a more permanent solution for the whole package in general given the comments from CRAN. So, do lookout for newer updates in the coming few months.

In the meantime, let me know if you encounter other problems and I will do the necessary fixes right away.

I will close this issue now but if you do get some more bugs related to this, feel free to re-open the issue or just raise another issue.

Thank you!
